  const Database_Dish = [
    {
        id: 0,
        title: 'Gemüse Pakoras',
        comment: 'frisches Gemüse in Kichererbsenmehl gebacken',
        price: 4.60,
        quantity: 0,
        groupID: 0,
    },
    {
        id: 1,
        title: 'Paneer Pakoras',
        comment: 'Käse in Kichererbsenmehl gebacken',
        price: 6.50,
        quantity: 0,
        groupID: 0,
    },
    {
        id: 2,
        title: 'Onion Bhaji',
        comment: 'Zwiebeln in Kichererbsenmehl gebacken',
        price: 4.60,
        quantity: 0,
        groupID: 0,
    },
    {
        id: 3,
        title: 'Chicken Pakoras',
        comment: 'Hähchenstücke in Kicherebsenmehl gebacken',
        price: 6.50,
        quantity: 0,
        groupID: 0,
    },
    {
        id: 4,
        title: 'Vegetable Samosa (2 Stück)',
        comment: 'Pastetchen mit frischem Gemüse gefüllt',
        price: 6.50,
        quantity: 0,
        groupID: 0,
    },
    {
        id: 5,
        title: 'Gemischte Vorspeisen (für 2 Personen)',
        comment: 'mit Onions, Bhajia, Chicken, Pakoras, Vegetable Pakoras und Paneer Pakoras',
        price: 13.50,
        quantity: 0,
        groupID: 0,
    },
    {
        id: 6,
        title: 'Papadam (2 Stück)',
        comment: 'hauchdünne, gewürzte Linsenfladen',
        price: 3.60,
        quantity: 0,
        groupID: 0,
    },
    {
        id: 7,
        title: 'Dal Suppe',
        comment: 'Linsensuppe',
        price: 3.90,
        quantity: 0,
        groupID: 1,
    },
    {
        id: 8,
        title: 'Sabji Suppe',
        comment: 'indische Gemüsesuppe',
        price: 3.90,
        quantity: 0,
        groupID: 1,
    },
    {
        id: 9,
        title: 'Tomatensuppe',
        comment: 'frische Tomatencremesuppe',
        price: 4.50,
        quantity: 0,
        groupID: 1,
    },
    {
        id: 10,
        title: 'Chicken Creme Soup',
        comment: 'Hühnercremesuppe',
        price: 4.80,
        quantity: 0,
        groupID: 1,
    },
    {
        id: 11,
        title: 'Malkatani Suppe',
        comment: 'mit Linsen, Reis und Hühnerfleisch',
        price: 4.80,
        quantity: 0,
        groupID: 1,
    },
    {
        id: 12,
        title: 'Channa Chat',
        comment: 'Kichererbsen mit Kartoffeln, Tomaten, Zwiebeln und Joghurtsauce',
        price: 5.50,
        quantity: 0,
        groupID: 2,
    },
    {
        id: 13,
        title: 'Gemischter Salat',
        comment: 'mit verschiedenem gemischten Salaten',
        price: 4.90,
        quantity: 0,
        groupID: 2,
    },
    {
        id: 14,
        title: 'Firteen salate',
        comment: 'It is firteen salate',
        price: 8.50,
        quantity: 0,
        groupID: 2,
    },
    {
        id: 15,
        title: 'Fifteen salate',
        comment: 'It is fifteen salate',
        price: 9.50,
        quantity: 0,
        groupID: 2,
    },
    {
        id: 16,
        title: 'Sixteen salate',
        comment: 'It is sixteen salate',
        price: 7.50,
        quantity: 0,
        groupID: 2,
    },
    {
        id: 17,
        title: 'Seventeen Beilagen',
        comment: 'It is Seventeen Beilagen',
        price: 4.5,
        quantity: 0,
        groupID: 3,
    },
    {
        id: 18,
        title: 'Eighteen Beilagen',
        comment: 'It is Eighteen Beilagen',
        price: 6.8,
        quantity: 0,
        groupID: 3,
    },
    {
        id: 19,
        title: 'Nineteen Beilagen',
        comment: 'It is Nineteen Beilagen',
        price: 3.6,
        quantity: 0,
        groupID: 3,
    },
    {
        id: 20,
        title: 'Twenty Beilagen',
        comment: 'It is Twenty Beilagen',
        price: 5.2,
        quantity: 0,
        groupID: 3,
    },
    {
        id: 21,
        title: 'TwoOne Beilagen',
        comment: 'It is TwoOne Beilagen',
        price: 7.3,
        quantity: 0,
        groupID: 3,
    },
    {
        id: 22,
        title: 'DoubleTwo Beilagen',
        comment: 'It is DoubleTwo Beilagen',
        price: 4.2,
        quantity: 0,
        groupID: 3,
    },
    {
        id: 23,
        title: 'TowThree Beilagen',
        comment: 'It is TowThree Beilagen',
        price: 6.8,
        quantity: 0,
        groupID: 3,
    },
    {
        id: 24,
        title: 'TwoFour Beilagen',
        comment: 'It is TwoFour Beilagen',
        price: 6.1,
        quantity: 0,
        groupID: 3,
    },
    {
        id: 25,
        title: 'TowThree Beilagen',
        comment: 'It is TowThree Beilagen',
        price: 6.8,
        quantity: 0,
        groupID: 4,
    },
    {
        id: 26,
        title: 'TwoFour Beilagen',
        comment: 'It is TwoFour Beilagen',
        price: 6.1,
        quantity: 0,
        groupID: 4,
    },
    {
        id: 27,
        title: 'TowThree Beilagen',
        comment: 'It is TowThree Beilagen',
        price: 6.8,
        quantity: 0,
        groupID: 4,
    },
    {
        id: 28,
        title: 'TwoFour Beilagen',
        comment: 'It is TwoFour Beilagen',
        price: 6.1,
        quantity: 0,
        groupID: 4,
    },
    {
        id: 29,
        title: 'TowThree Beilagen',
        comment: 'It is TowThree Beilagen',
        price: 6.8,
        quantity: 0,
        groupID: 4,
    },
    {
        id: 30,
        title: 'TwoFour Beilagen',
        comment: 'It is TwoFour Beilagen',
        price: 6.1,
        quantity: 0,
        groupID: 4,
    },
    {
        id: 31,
        title: 'TowThree Beilagen',
        comment: 'It is TowThree Beilagen',
        price: 6.8,
        quantity: 0,
        groupID: 4,
    },
    {
        id: 32,
        title: 'TwoFour Beilagen',
        comment: 'It is TwoFour Beilagen',
        price: 6.1,
        quantity: 0,
        groupID: 4,
    },
    {
        id: 33,
        title: 'ThreeThree Beilagen',
        comment: 'It is TowThree Beilagen',
        price: 6.8,
        quantity: 0,
        groupID: 5,
    },
    {
        id: 34,
        title: 'ThreeFour Beilagen',
        comment: 'It is ThreeFour Beilagen',
        price: 6.1,
        quantity: 0,
        groupID: 5,
    },
    {
        id: 35,
        title: 'ThreeFive Beilagen',
        comment: 'It is TowThree Beilagen',
        price: 6.8,
        quantity: 0,
        groupID: 5,
    },
    {
        id: 36,
        title: 'TwoFour Gekdi Beilagen',
        comment: 'It is TwoFouFour Carlr Beilagen',
        price: 6.1,
        quantity: 0,
        groupID: 5,
    },
    {
        id: 37,
        title: 'TowThree Idenio Beilagen',
        comment: 'It is Four Carl TowThree Beilagen',
        price: 6.8,
        quantity: 0,
        groupID: 5,
    },
    {
        id: 38,
        title: 'TwoFour Andie Beilagen',
        comment: 'It is TwoFour Four Carl Beilagen',
        price: 6.1,
        quantity: 0,
        groupID: 5,
    },
    {
        id: 39,
        title: 'TowThree Louis Beilagen',
        comment: 'It is Tow Four Carl Three Beilagen',
        price: 6.8,
        quantity: 0,
        groupID: 5,
    },
    {
        id: 40,
        title: 'TwoFour Carl Beilagen',
        comment: 'It is TwoFour Four Carl Beilagen',
        price: 6.1,
        quantity: 0,
        groupID: 5,
    },
    
  ]

  export default Database_Dish;